spring:
  servlet:
    multipart:
      max-file-size: 100MB
  datasource:
    url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/lgikitpy
    username: lgikitpy
    password: 6ZtwOXwzjhQfkWGhQ0y_0e1hD4ay_o1Q
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
  flyway:
    enabled: true

jwt:
  secret: usersecret

